version: "3.5"

services:
  public-service:
    image: localhost/adidas-be-challenge-publicservice:latest
    container_name: adidas-be-challenge-publicservice
    build:
      context: public-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - public_network
      - private_network
    environment:
      - PRIORITY_SALE_SERVICE_URL=http://priority-sale-service:8082
      - ADI_CLUB_SERVICE_URL=http://adi-club-service:8081
    links:
      - "priority-sale-service"

  priority-sale-service:
    image: localhost/adidas-be-challenge-prioritysaleservice:latest
    container_name: adidas-be-challenge-prioritysaleservice
    environment:
      - EMAIL_SERVICE_URL=http://email-service:8083
    build:
      context: priority-sale-service
      dockerfile: Dockerfile
    networks:
      - private_network
    ports:
      - "8082:8082"
    links:
      - "adi-club-service"
      - "email-service"

  adi-club-service:
    image: localhost/adidas-be-challenge-adiclubservice:latest
    container_name: adidas-be-challenge-adiclubservice
    build:
      context: adiclub-service
      dockerfile: Dockerfile
    networks:
      - private_network
    ports:
      - "8081:8081"

  email-service:
    image: localhost/adidas-be-challenge-emailservice:latest
    container_name: adidas-be-challenge-emailservice
    build:
      context: email-service
      dockerfile: Dockerfile
    networks:
      - private_network
    ports:
      - "8083:8083"
networks:
  public_network:
      name: public_network
      driver: bridge
      external: true
  private_network:
      name: private_network
      internal: true
      external: false

